default: &default
  mode:    proxy        # allowed: master|proxy
  site_id: 9999         # ID of the site this service is runnig on.
  master_uri:           # URI of the master instance, if mode=proxy
  remote_http_options:  # options for remote HTTP operations:
    user:             # user name to use for basic auth 
    password:         # password to use for basic auth 
    timeout:      10  # data timout - increase for connections known to be slow, decrease to allow faster feedback on broken lines
    open_timeout: 10  # open_timout, same as above

development:
  <<: *default
  mode: proxy
  site_id: 4
  master_uri: http://localhost:3002
  remote_http_options:
    user:         test
    password:     test
    timeout:      10
    open_timeout: 10

integration:
  mode: master
  site_id: 0

